name: build

on:
  push:
    branches-ignore:
      - main
      - future/readme

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v1
        - name: build Dockerfile
          run: |
            docker build . -t superml
            docker run --rm sumperml sh -c "python3 -c 'import graphviz' && python3 -c 'import matplotlib' && python3 -c 'import MeCab' && python3 -c 'import numpy' && python3 -c 'import pandas' && python3 -c 'import seaborn' && python3 -c 'import tensorflow'""
