name: build

on:
  push:
    branches-ignore:
      - main
      - future/readme

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v1
        - name: build Dockerfile
          run: |
            docker build . -t superml
            bash .github/workflows/import_test.sh
