name: push_image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v1
        - name: build Dockerfile
          run:
            docker build . -t superml
        - name: push Image to Pacakge
          run: |
            echo ${{ secrets.GHCR }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker build . -t superml
            docker tag superml ghcr.io/${{ github.actor }}/${{ github.repository }}/superml:latest
            docker push ghcr.io/${{ github.actor }}/${{ github.repository }}/superml:latest
